@echo off
cd /d "%~dp0"
rmdir /S /Q release
mkdir release
mkdir release\experimental
mkdir release\experimental_steamclient
mkdir release\debug_experimental
mkdir release\debug_experimental_steamclient
call build_set_protobuf_directories.bat
"%PROTOC_X86_EXE%" -I.\dll\ --cpp_out=.\dll\ .\dll\net.proto
call build_env_x86.bat
rmdir /S /Q deps
mkdir deps
cl /Fo:deps/ /c /EHsc /Ox /MP4 /DEMU_RELEASE_BUILD /DNDEBUG /I%PROTOBUF_X86_DIRECTORY%\include\ /IImGui /Ioverlay_experimental dll/net.pb.cc detours/creatwth.cpp detours/detours.cpp detours/disasm.cpp detours/disolarm.cpp detours/disolarm64.cpp detours/disolia64.cpp detours/disolx64.cpp detours/disolx86.cpp detours/image.cpp detours/modules.cpp controller/gamepad.c ImGui/imgui.cpp ImGui/imgui_draw.cpp ImGui/imgui_tables.cpp ImGui/imgui_widgets.cpp ImGui/backends/imgui_impl_dx9.cpp ImGui/backends/imgui_impl_dx10.cpp ImGui/backends/imgui_impl_dx11.cpp ImGui/backends/imgui_impl_dx12.cpp ImGui/backends/imgui_impl_win32.cpp ImGui/backends/imgui_impl_vulkan.cpp ImGui/backends/imgui_impl_opengl3.cpp ImGui/backends/imgui_win_shader_blobs.cpp overlay_experimental/System/Encoding.cpp overlay_experimental/System/Filesystem.cpp overlay_experimental/System/Library.cpp overlay_experimental/System/String.cpp overlay_experimental/System/System.cpp overlay_experimental/System/System_internals.cpp
cl /LD /EHsc /Ox /MP4 /DEMU_RELEASE_BUILD /DNDEBUG /I%PROTOBUF_X86_DIRECTORY%\include\ /IImGui /Ioverlay_experimental dll/base.cpp dll/local_storage.cpp dll/network.cpp dll/settings.cpp dll/settings_parser.cpp dll/steam_applist.cpp dll/steam_apps.cpp dll/steam_client.cpp dll/steam_gameserver.cpp dll/steam_gameserverstats.cpp dll/steam_http.cpp dll/steam_matchmaking_servers.cpp dll/steam_music.cpp dll/steam_musicremote.cpp dll/steam_parental.cpp dll/steam_screenshots.cpp dll/steam_video.cpp dll/wrap.cpp dll/flat.cpp dll/dll.cpp deps/net.pb.obj "%PROTOBUF_X86_LIBRARY%" Iphlpapi.lib Ws2_32.lib Shell32.lib /link /debug:none /OUT:release\steam_api.dll
rmdir /S /Q deps_sc
mkdir deps_sc
cl /Fo:deps_sc/ /c /EHsc /Ox /MP4 /DEMU_EXPERIMENTAL_BUILD /DCONTROLLER_SUPPORT /DEMU_OVERLAY /I%PROTOBUF_X86_DIRECTORY%\include\ /IImGui /Ioverlay_experimental dll/base.cpp dll/local_storage.cpp dll/network.cpp dll/settings.cpp dll/settings_parser.cpp dll/steam_applist.cpp dll/steam_apps.cpp dll/steam_client.cpp dll/steam_gameserver.cpp dll/steam_gameserverstats.cpp dll/steam_http.cpp dll/steam_matchmaking_servers.cpp dll/steam_music.cpp dll/steam_musicremote.cpp dll/steam_parental.cpp dll/steam_screenshots.cpp dll/steam_video.cpp dll/wrap.cpp overlay_experimental/Base_Hook.cpp overlay_experimental/Renderer_Detector.cpp overlay_experimental/steam_overlay.cpp overlay_experimental/windows/DX10_Hook.cpp overlay_experimental/windows/DX11_Hook.cpp overlay_experimental/windows/DX12_Hook.cpp overlay_experimental/windows/DX9_Hook.cpp overlay_experimental/windows/OpenGL_Hook.cpp overlay_experimental/windows/Vulkan_Hook.cpp overlay_experimental/windows/vulkan_lib.cpp overlay_experimental/windows/Windows_Hook.cpp
cl /LD /EHsc /Ox /MP4 /DEMU_EXPERIMENTAL_BUILD /DCONTROLLER_SUPPORT /DEMU_OVERLAY /I%PROTOBUF_X86_DIRECTORY%\include\ /IImGui /Ioverlay_experimental dll/flat.cpp dll/dll.cpp deps/net.pb.obj deps/creatwth.obj deps/detours.obj deps/disasm.obj deps/disolarm.obj deps/disolarm64.obj deps/disolia64.obj deps/disolx64.obj deps/disolx86.obj deps/image.obj deps/modules.obj deps/gamepad.obj deps/imgui.obj deps/imgui_draw.obj deps/imgui_tables.obj deps/imgui_widgets.obj deps/imgui_impl_dx9.obj deps/imgui_impl_dx10.obj deps/imgui_impl_dx11.obj deps/imgui_impl_dx12.obj deps/imgui_impl_win32.obj deps/imgui_impl_vulkan.obj deps/imgui_impl_opengl3.obj deps/imgui_win_shader_blobs.obj deps/Encoding.obj deps/Filesystem.obj deps/Library.obj deps/String.obj deps/System.obj deps/System_internals.obj deps_sc/base.obj deps_sc/local_storage.obj deps_sc/network.obj deps_sc/settings.obj deps_sc/settings_parser.obj deps_sc/steam_applist.obj deps_sc/steam_apps.obj deps_sc/steam_client.obj deps_sc/steam_gameserver.obj deps_sc/steam_gameserverstats.obj deps_sc/steam_http.obj deps_sc/steam_matchmaking_servers.obj deps_sc/steam_music.obj deps_sc/steam_musicremote.obj deps_sc/steam_parental.obj deps_sc/steam_screenshots.obj deps_sc/steam_video.obj deps_sc/wrap.obj deps_sc/Base_Hook.obj deps_sc/Renderer_Detector.obj deps_sc/steam_overlay.obj deps_sc/DX10_Hook.obj deps_sc/DX11_Hook.obj deps_sc/DX12_Hook.obj deps_sc/DX9_Hook.obj deps_sc/OpenGL_Hook.obj deps_sc/Vulkan_Hook.obj deps_sc/vulkan_lib.obj deps_sc/Windows_Hook.obj "%PROTOBUF_X86_LIBRARY%" opengl32.lib Winmm.lib Iphlpapi.lib Ws2_32.lib Shell32.lib /link /OUT:release\debug_experimental\steam_api.dll
cl /LD /DSTEAMCLIENT_DLL /EHsc /Ox /MP4 /DEMU_EXPERIMENTAL_BUILD /DCONTROLLER_SUPPORT /DEMU_OVERLAY /I%PROTOBUF_X86_DIRECTORY%\include\ /IImGui /Ioverlay_experimental dll/flat.cpp dll/dll.cpp deps/net.pb.obj deps/creatwth.obj deps/detours.obj deps/disasm.obj deps/disolarm.obj deps/disolarm64.obj deps/disolia64.obj deps/disolx64.obj deps/disolx86.obj deps/image.obj deps/modules.obj deps/gamepad.obj deps/imgui.obj deps/imgui_draw.obj deps/imgui_tables.obj deps/imgui_widgets.obj deps/imgui_impl_dx9.obj deps/imgui_impl_dx10.obj deps/imgui_impl_dx11.obj deps/imgui_impl_dx12.obj deps/imgui_impl_win32.obj deps/imgui_impl_vulkan.obj deps/imgui_impl_opengl3.obj deps/imgui_win_shader_blobs.obj deps/Encoding.obj deps/Filesystem.obj deps/Library.obj deps/String.obj deps/System.obj deps/System_internals.obj deps_sc/base.obj deps_sc/local_storage.obj deps_sc/network.obj deps_sc/settings.obj deps_sc/settings_parser.obj deps_sc/steam_applist.obj deps_sc/steam_apps.obj deps_sc/steam_client.obj deps_sc/steam_gameserver.obj deps_sc/steam_gameserverstats.obj deps_sc/steam_http.obj deps_sc/steam_matchmaking_servers.obj deps_sc/steam_music.obj deps_sc/steam_musicremote.obj deps_sc/steam_parental.obj deps_sc/steam_screenshots.obj deps_sc/steam_video.obj deps_sc/wrap.obj deps_sc/Base_Hook.obj deps_sc/Renderer_Detector.obj deps_sc/steam_overlay.obj deps_sc/DX10_Hook.obj deps_sc/DX11_Hook.obj deps_sc/DX12_Hook.obj deps_sc/DX9_Hook.obj deps_sc/OpenGL_Hook.obj deps_sc/Vulkan_Hook.obj deps_sc/vulkan_lib.obj deps_sc/Windows_Hook.obj "%PROTOBUF_X86_LIBRARY%" opengl32.lib Winmm.lib Iphlpapi.lib Ws2_32.lib Shell32.lib /link /OUT:release\debug_experimental_steamclient\steamclient.dll
rmdir /S /Q deps_sc
mkdir deps_sc
cl /Fo:deps_sc/ /c /EHsc /Ox /MP4 /DEMU_RELEASE_BUILD /DNDEBUG /DEMU_EXPERIMENTAL_BUILD /DCONTROLLER_SUPPORT /DEMU_OVERLAY /I%PROTOBUF_X86_DIRECTORY%\include\ /IImGui /Ioverlay_experimental dll/base.cpp dll/local_storage.cpp dll/network.cpp dll/settings.cpp dll/settings_parser.cpp dll/steam_applist.cpp dll/steam_apps.cpp dll/steam_client.cpp dll/steam_gameserver.cpp dll/steam_gameserverstats.cpp dll/steam_http.cpp dll/steam_matchmaking_servers.cpp dll/steam_music.cpp dll/steam_musicremote.cpp dll/steam_parental.cpp dll/steam_screenshots.cpp dll/steam_video.cpp dll/wrap.cpp overlay_experimental/Base_Hook.cpp overlay_experimental/Renderer_Detector.cpp overlay_experimental/steam_overlay.cpp overlay_experimental/windows/DX10_Hook.cpp overlay_experimental/windows/DX11_Hook.cpp overlay_experimental/windows/DX12_Hook.cpp overlay_experimental/windows/DX9_Hook.cpp overlay_experimental/windows/OpenGL_Hook.cpp overlay_experimental/windows/Vulkan_Hook.cpp overlay_experimental/windows/vulkan_lib.cpp overlay_experimental/windows/Windows_Hook.cpp
cl /LD /EHsc /Ox /MP4 /DEMU_RELEASE_BUILD /DNDEBUG /DEMU_EXPERIMENTAL_BUILD /DCONTROLLER_SUPPORT /DEMU_OVERLAY /I%PROTOBUF_X86_DIRECTORY%\include\ /IImGui /Ioverlay_experimental dll/flat.cpp dll/dll.cpp deps/net.pb.obj deps/creatwth.obj deps/detours.obj deps/disasm.obj deps/disolarm.obj deps/disolarm64.obj deps/disolia64.obj deps/disolx64.obj deps/disolx86.obj deps/image.obj deps/modules.obj deps/gamepad.obj deps/imgui.obj deps/imgui_draw.obj deps/imgui_tables.obj deps/imgui_widgets.obj deps/imgui_impl_dx9.obj deps/imgui_impl_dx10.obj deps/imgui_impl_dx11.obj deps/imgui_impl_dx12.obj deps/imgui_impl_win32.obj deps/imgui_impl_vulkan.obj deps/imgui_impl_opengl3.obj deps/imgui_win_shader_blobs.obj deps/Encoding.obj deps/Filesystem.obj deps/Library.obj deps/String.obj deps/System.obj deps/System_internals.obj deps_sc/base.obj deps_sc/local_storage.obj deps_sc/network.obj deps_sc/settings.obj deps_sc/settings_parser.obj deps_sc/steam_applist.obj deps_sc/steam_apps.obj deps_sc/steam_client.obj deps_sc/steam_gameserver.obj deps_sc/steam_gameserverstats.obj deps_sc/steam_http.obj deps_sc/steam_matchmaking_servers.obj deps_sc/steam_music.obj deps_sc/steam_musicremote.obj deps_sc/steam_parental.obj deps_sc/steam_screenshots.obj deps_sc/steam_video.obj deps_sc/wrap.obj deps_sc/Base_Hook.obj deps_sc/Renderer_Detector.obj deps_sc/steam_overlay.obj deps_sc/DX10_Hook.obj deps_sc/DX11_Hook.obj deps_sc/DX12_Hook.obj deps_sc/DX9_Hook.obj deps_sc/OpenGL_Hook.obj deps_sc/Vulkan_Hook.obj deps_sc/vulkan_lib.obj deps_sc/Windows_Hook.obj "%PROTOBUF_X86_LIBRARY%" opengl32.lib Winmm.lib Iphlpapi.lib Ws2_32.lib Shell32.lib /link /debug:none /OUT:release\experimental\steam_api.dll
cl /LD /DSTEAMCLIENT_DLL /EHsc /Ox /MP4 /DEMU_RELEASE_BUILD /DNDEBUG /DEMU_EXPERIMENTAL_BUILD /DCONTROLLER_SUPPORT /DEMU_OVERLAY /I%PROTOBUF_X86_DIRECTORY%\include\ /IImGui /Ioverlay_experimental dll/flat.cpp dll/dll.cpp deps/net.pb.obj deps/creatwth.obj deps/detours.obj deps/disasm.obj deps/disolarm.obj deps/disolarm64.obj deps/disolia64.obj deps/disolx64.obj deps/disolx86.obj deps/image.obj deps/modules.obj deps/gamepad.obj deps/imgui.obj deps/imgui_draw.obj deps/imgui_tables.obj deps/imgui_widgets.obj deps/imgui_impl_dx9.obj deps/imgui_impl_dx10.obj deps/imgui_impl_dx11.obj deps/imgui_impl_dx12.obj deps/imgui_impl_win32.obj deps/imgui_impl_vulkan.obj deps/imgui_impl_opengl3.obj deps/imgui_win_shader_blobs.obj deps/Encoding.obj deps/Filesystem.obj deps/Library.obj deps/String.obj deps/System.obj deps/System_internals.obj deps_sc/base.obj deps_sc/local_storage.obj deps_sc/network.obj deps_sc/settings.obj deps_sc/settings_parser.obj deps_sc/steam_applist.obj deps_sc/steam_apps.obj deps_sc/steam_client.obj deps_sc/steam_gameserver.obj deps_sc/steam_gameserverstats.obj deps_sc/steam_http.obj deps_sc/steam_matchmaking_servers.obj deps_sc/steam_music.obj deps_sc/steam_musicremote.obj deps_sc/steam_parental.obj deps_sc/steam_screenshots.obj deps_sc/steam_video.obj deps_sc/wrap.obj deps_sc/Base_Hook.obj deps_sc/Renderer_Detector.obj deps_sc/steam_overlay.obj deps_sc/DX10_Hook.obj deps_sc/DX11_Hook.obj deps_sc/DX12_Hook.obj deps_sc/DX9_Hook.obj deps_sc/OpenGL_Hook.obj deps_sc/Vulkan_Hook.obj deps_sc/vulkan_lib.obj deps_sc/Windows_Hook.obj "%PROTOBUF_X86_LIBRARY%" opengl32.lib Winmm.lib Iphlpapi.lib Ws2_32.lib Shell32.lib /link /debug:none /OUT:release\experimental_steamclient\steamclient.dll
cl /LD /DEMU_RELEASE_BUILD /DNDEBUG /DEMU_EXPERIMENTAL_BUILD /DCONTROLLER_SUPPORT /DEMU_OVERLAY steamclient.cpp /EHsc /Ox /MP4 /link /debug:none /OUT:release\experimental\steamclient.dll
cl steamclient_loader/ColdClientLoader.cpp advapi32.lib user32.lib /EHsc /Ox /MP4 /link /debug:none /OUT:release\experimental_steamclient\steamclient_loader.exe
"%PROTOC_X64_EXE%" -I.\dll\ --cpp_out=.\dll\ .\dll\net.proto
call build_env_x64.bat
rmdir /S /Q deps
mkdir deps
cl /Fo:deps/ /c /EHsc /Ox /MP4 /DEMU_RELEASE_BUILD /DNDEBUG /I%PROTOBUF_X64_DIRECTORY%\include\ /IImGui /Ioverlay_experimental dll/net.pb.cc detours/creatwth.cpp detours/detours.cpp detours/disasm.cpp detours/disolarm.cpp detours/disolarm64.cpp detours/disolia64.cpp detours/disolx64.cpp detours/disolx86.cpp detours/image.cpp detours/modules.cpp controller/gamepad.c ImGui/imgui.cpp ImGui/imgui_draw.cpp ImGui/imgui_tables.cpp ImGui/imgui_widgets.cpp ImGui/backends/imgui_impl_dx9.cpp ImGui/backends/imgui_impl_dx10.cpp ImGui/backends/imgui_impl_dx11.cpp ImGui/backends/imgui_impl_dx12.cpp ImGui/backends/imgui_impl_win32.cpp ImGui/backends/imgui_impl_vulkan.cpp ImGui/backends/imgui_impl_opengl3.cpp ImGui/backends/imgui_win_shader_blobs.cpp overlay_experimental/System/Encoding.cpp overlay_experimental/System/Filesystem.cpp overlay_experimental/System/Library.cpp overlay_experimental/System/String.cpp overlay_experimental/System/System.cpp overlay_experimental/System/System_internals.cpp
cl /LD /EHsc /Ox /MP4 /DEMU_RELEASE_BUILD /DNDEBUG /I%PROTOBUF_X64_DIRECTORY%\include\ /IImGui /Ioverlay_experimental dll/base.cpp dll/local_storage.cpp dll/network.cpp dll/settings.cpp dll/settings_parser.cpp dll/steam_applist.cpp dll/steam_apps.cpp dll/steam_client.cpp dll/steam_gameserver.cpp dll/steam_gameserverstats.cpp dll/steam_http.cpp dll/steam_matchmaking_servers.cpp dll/steam_music.cpp dll/steam_musicremote.cpp dll/steam_parental.cpp dll/steam_screenshots.cpp dll/steam_video.cpp dll/wrap.cpp dll/flat.cpp dll/dll.cpp deps/net.pb.obj "%PROTOBUF_X64_LIBRARY%" Iphlpapi.lib Ws2_32.lib Shell32.lib /link /debug:none /OUT:release\steam_api64.dll
rmdir /S /Q deps_sc
mkdir deps_sc
cl /Fo:deps_sc/ /c /EHsc /Ox /MP4 /DEMU_EXPERIMENTAL_BUILD /DCONTROLLER_SUPPORT /DEMU_OVERLAY /I%PROTOBUF_X64_DIRECTORY%\include\ /IImGui /Ioverlay_experimental dll/base.cpp dll/local_storage.cpp dll/network.cpp dll/settings.cpp dll/settings_parser.cpp dll/steam_applist.cpp dll/steam_apps.cpp dll/steam_client.cpp dll/steam_gameserver.cpp dll/steam_gameserverstats.cpp dll/steam_http.cpp dll/steam_matchmaking_servers.cpp dll/steam_music.cpp dll/steam_musicremote.cpp dll/steam_parental.cpp dll/steam_screenshots.cpp dll/steam_video.cpp dll/wrap.cpp overlay_experimental/Base_Hook.cpp overlay_experimental/Renderer_Detector.cpp overlay_experimental/steam_overlay.cpp overlay_experimental/windows/DX10_Hook.cpp overlay_experimental/windows/DX11_Hook.cpp overlay_experimental/windows/DX12_Hook.cpp overlay_experimental/windows/DX9_Hook.cpp overlay_experimental/windows/OpenGL_Hook.cpp overlay_experimental/windows/Vulkan_Hook.cpp overlay_experimental/windows/vulkan_lib.cpp overlay_experimental/windows/Windows_Hook.cpp
cl /LD /EHsc /Ox /MP4 /DEMU_EXPERIMENTAL_BUILD /DCONTROLLER_SUPPORT /DEMU_OVERLAY /I%PROTOBUF_X64_DIRECTORY%\include\ /IImGui /Ioverlay_experimental dll/flat.cpp dll/dll.cpp deps/net.pb.obj deps/creatwth.obj deps/detours.obj deps/disasm.obj deps/disolarm.obj deps/disolarm64.obj deps/disolia64.obj deps/disolx64.obj deps/disolx86.obj deps/image.obj deps/modules.obj deps/gamepad.obj deps/imgui.obj deps/imgui_draw.obj deps/imgui_tables.obj deps/imgui_widgets.obj deps/imgui_impl_dx9.obj deps/imgui_impl_dx10.obj deps/imgui_impl_dx11.obj deps/imgui_impl_dx12.obj deps/imgui_impl_win32.obj deps/imgui_impl_vulkan.obj deps/imgui_impl_opengl3.obj deps/imgui_win_shader_blobs.obj deps/Encoding.obj deps/Filesystem.obj deps/Library.obj deps/String.obj deps/System.obj deps/System_internals.obj deps_sc/base.obj deps_sc/local_storage.obj deps_sc/network.obj deps_sc/settings.obj deps_sc/settings_parser.obj deps_sc/steam_applist.obj deps_sc/steam_apps.obj deps_sc/steam_client.obj deps_sc/steam_gameserver.obj deps_sc/steam_gameserverstats.obj deps_sc/steam_http.obj deps_sc/steam_matchmaking_servers.obj deps_sc/steam_music.obj deps_sc/steam_musicremote.obj deps_sc/steam_parental.obj deps_sc/steam_screenshots.obj deps_sc/steam_video.obj deps_sc/wrap.obj deps_sc/Base_Hook.obj deps_sc/Renderer_Detector.obj deps_sc/steam_overlay.obj deps_sc/DX10_Hook.obj deps_sc/DX11_Hook.obj deps_sc/DX12_Hook.obj deps_sc/DX9_Hook.obj deps_sc/OpenGL_Hook.obj deps_sc/Vulkan_Hook.obj deps_sc/vulkan_lib.obj deps_sc/Windows_Hook.obj "%PROTOBUF_X64_LIBRARY%" opengl32.lib Winmm.lib Iphlpapi.lib Ws2_32.lib Shell32.lib /link /OUT:release\debug_experimental\steam_api64.dll
cl /LD /DSTEAMCLIENT_DLL /EHsc /Ox /MP4 /DEMU_EXPERIMENTAL_BUILD /DCONTROLLER_SUPPORT /DEMU_OVERLAY /I%PROTOBUF_X64_DIRECTORY%\include\ /IImGui /Ioverlay_experimental dll/flat.cpp dll/dll.cpp deps/net.pb.obj deps/creatwth.obj deps/detours.obj deps/disasm.obj deps/disolarm.obj deps/disolarm64.obj deps/disolia64.obj deps/disolx64.obj deps/disolx86.obj deps/image.obj deps/modules.obj deps/gamepad.obj deps/imgui.obj deps/imgui_draw.obj deps/imgui_tables.obj deps/imgui_widgets.obj deps/imgui_impl_dx9.obj deps/imgui_impl_dx10.obj deps/imgui_impl_dx11.obj deps/imgui_impl_dx12.obj deps/imgui_impl_win32.obj deps/imgui_impl_vulkan.obj deps/imgui_impl_opengl3.obj deps/imgui_win_shader_blobs.obj deps/Encoding.obj deps/Filesystem.obj deps/Library.obj deps/String.obj deps/System.obj deps/System_internals.obj deps_sc/base.obj deps_sc/local_storage.obj deps_sc/network.obj deps_sc/settings.obj deps_sc/settings_parser.obj deps_sc/steam_applist.obj deps_sc/steam_apps.obj deps_sc/steam_client.obj deps_sc/steam_gameserver.obj deps_sc/steam_gameserverstats.obj deps_sc/steam_http.obj deps_sc/steam_matchmaking_servers.obj deps_sc/steam_music.obj deps_sc/steam_musicremote.obj deps_sc/steam_parental.obj deps_sc/steam_screenshots.obj deps_sc/steam_video.obj deps_sc/wrap.obj deps_sc/Base_Hook.obj deps_sc/Renderer_Detector.obj deps_sc/steam_overlay.obj deps_sc/DX10_Hook.obj deps_sc/DX11_Hook.obj deps_sc/DX12_Hook.obj deps_sc/DX9_Hook.obj deps_sc/OpenGL_Hook.obj deps_sc/Vulkan_Hook.obj deps_sc/vulkan_lib.obj deps_sc/Windows_Hook.obj "%PROTOBUF_X64_LIBRARY%" opengl32.lib Winmm.lib Iphlpapi.lib Ws2_32.lib Shell32.lib /link /OUT:release\debug_experimental_steamclient\steamclient64.dll
rmdir /S /Q deps_sc
mkdir deps_sc
cl /Fo:deps_sc/ /c /EHsc /Ox /MP4 /DEMU_RELEASE_BUILD /DNDEBUG /DEMU_EXPERIMENTAL_BUILD /DCONTROLLER_SUPPORT /DEMU_OVERLAY /I%PROTOBUF_X64_DIRECTORY%\include\ /IImGui /Ioverlay_experimental dll/base.cpp dll/local_storage.cpp dll/network.cpp dll/settings.cpp dll/settings_parser.cpp dll/steam_applist.cpp dll/steam_apps.cpp dll/steam_client.cpp dll/steam_gameserver.cpp dll/steam_gameserverstats.cpp dll/steam_http.cpp dll/steam_matchmaking_servers.cpp dll/steam_music.cpp dll/steam_musicremote.cpp dll/steam_parental.cpp dll/steam_screenshots.cpp dll/steam_video.cpp dll/wrap.cpp overlay_experimental/Base_Hook.cpp overlay_experimental/Renderer_Detector.cpp overlay_experimental/steam_overlay.cpp overlay_experimental/windows/DX10_Hook.cpp overlay_experimental/windows/DX11_Hook.cpp overlay_experimental/windows/DX12_Hook.cpp overlay_experimental/windows/DX9_Hook.cpp overlay_experimental/windows/OpenGL_Hook.cpp overlay_experimental/windows/Vulkan_Hook.cpp overlay_experimental/windows/vulkan_lib.cpp overlay_experimental/windows/Windows_Hook.cpp
cl /LD /EHsc /Ox /MP4 /DEMU_RELEASE_BUILD /DNDEBUG /DEMU_EXPERIMENTAL_BUILD /DCONTROLLER_SUPPORT /DEMU_OVERLAY /I%PROTOBUF_X64_DIRECTORY%\include\ /IImGui /Ioverlay_experimental dll/flat.cpp dll/dll.cpp deps/net.pb.obj deps/creatwth.obj deps/detours.obj deps/disasm.obj deps/disolarm.obj deps/disolarm64.obj deps/disolia64.obj deps/disolx64.obj deps/disolx86.obj deps/image.obj deps/modules.obj deps/gamepad.obj deps/imgui.obj deps/imgui_draw.obj deps/imgui_tables.obj deps/imgui_widgets.obj deps/imgui_impl_dx9.obj deps/imgui_impl_dx10.obj deps/imgui_impl_dx11.obj deps/imgui_impl_dx12.obj deps/imgui_impl_win32.obj deps/imgui_impl_vulkan.obj deps/imgui_impl_opengl3.obj deps/imgui_win_shader_blobs.obj deps/Encoding.obj deps/Filesystem.obj deps/Library.obj deps/String.obj deps/System.obj deps/System_internals.obj deps_sc/base.obj deps_sc/local_storage.obj deps_sc/network.obj deps_sc/settings.obj deps_sc/settings_parser.obj deps_sc/steam_applist.obj deps_sc/steam_apps.obj deps_sc/steam_client.obj deps_sc/steam_gameserver.obj deps_sc/steam_gameserverstats.obj deps_sc/steam_http.obj deps_sc/steam_matchmaking_servers.obj deps_sc/steam_music.obj deps_sc/steam_musicremote.obj deps_sc/steam_parental.obj deps_sc/steam_screenshots.obj deps_sc/steam_video.obj deps_sc/wrap.obj deps_sc/Base_Hook.obj deps_sc/Renderer_Detector.obj deps_sc/steam_overlay.obj deps_sc/DX10_Hook.obj deps_sc/DX11_Hook.obj deps_sc/DX12_Hook.obj deps_sc/DX9_Hook.obj deps_sc/OpenGL_Hook.obj deps_sc/Vulkan_Hook.obj deps_sc/vulkan_lib.obj deps_sc/Windows_Hook.obj "%PROTOBUF_X64_LIBRARY%" opengl32.lib Winmm.lib Iphlpapi.lib Ws2_32.lib Shell32.lib /link /debug:none /OUT:release\experimental\steam_api64.dll
cl /LD /DSTEAMCLIENT_DLL /EHsc /Ox /MP4 /DEMU_RELEASE_BUILD /DNDEBUG /DEMU_EXPERIMENTAL_BUILD /DCONTROLLER_SUPPORT /DEMU_OVERLAY /I%PROTOBUF_X64_DIRECTORY%\include\ /IImGui /Ioverlay_experimental dll/flat.cpp dll/dll.cpp deps/net.pb.obj deps/creatwth.obj deps/detours.obj deps/disasm.obj deps/disolarm.obj deps/disolarm64.obj deps/disolia64.obj deps/disolx64.obj deps/disolx86.obj deps/image.obj deps/modules.obj deps/gamepad.obj deps/imgui.obj deps/imgui_draw.obj deps/imgui_tables.obj deps/imgui_widgets.obj deps/imgui_impl_dx9.obj deps/imgui_impl_dx10.obj deps/imgui_impl_dx11.obj deps/imgui_impl_dx12.obj deps/imgui_impl_win32.obj deps/imgui_impl_vulkan.obj deps/imgui_impl_opengl3.obj deps/imgui_win_shader_blobs.obj deps/Encoding.obj deps/Filesystem.obj deps/Library.obj deps/String.obj deps/System.obj deps/System_internals.obj deps_sc/base.obj deps_sc/local_storage.obj deps_sc/network.obj deps_sc/settings.obj deps_sc/settings_parser.obj deps_sc/steam_applist.obj deps_sc/steam_apps.obj deps_sc/steam_client.obj deps_sc/steam_gameserver.obj deps_sc/steam_gameserverstats.obj deps_sc/steam_http.obj deps_sc/steam_matchmaking_servers.obj deps_sc/steam_music.obj deps_sc/steam_musicremote.obj deps_sc/steam_parental.obj deps_sc/steam_screenshots.obj deps_sc/steam_video.obj deps_sc/wrap.obj deps_sc/Base_Hook.obj deps_sc/Renderer_Detector.obj deps_sc/steam_overlay.obj deps_sc/DX10_Hook.obj deps_sc/DX11_Hook.obj deps_sc/DX12_Hook.obj deps_sc/DX9_Hook.obj deps_sc/OpenGL_Hook.obj deps_sc/Vulkan_Hook.obj deps_sc/vulkan_lib.obj deps_sc/Windows_Hook.obj "%PROTOBUF_X64_LIBRARY%" opengl32.lib Winmm.lib Iphlpapi.lib Ws2_32.lib Shell32.lib /link /debug:none /OUT:release\experimental_steamclient\steamclient64.dll
cl /LD /DEMU_RELEASE_BUILD /DNDEBUG /DEMU_EXPERIMENTAL_BUILD /DCONTROLLER_SUPPORT /DEMU_OVERLAY steamclient.cpp /EHsc /Ox /MP4 /link /debug:none /OUT:release\experimental\steamclient64.dll

copy Readme_release.txt release\Readme.txt
xcopy /s files_example\* release\
copy Readme_experimental.txt release\experimental\Readme.txt
copy Readme_debug.txt release\debug_experimental\Readme.txt
copy steamclient_loader\ColdClientLoader.ini release\experimental_steamclient\
call build_win_lobby_connect.bat
call build_win_find_interfaces.bat
